# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for VOID HUNTER (BLOQUE 54 + 58.next fix).

Builds a SINGLE-FILE distribution `dist/void-hunter.exe` (onefile mode).
BLOQUE 58.next fix: switched from onedir to onefile so users can download
ONE .exe and run it without needing a companion _internal/ folder. The
onedir mode created a `._internal` Python311.dll dependency that failed
with "Failed to load Python DLL" if the .exe was extracted alone.

Usage:
    pyinstaller build.spec            # one-time build
    pyinstaller build.spec --clean    # nuke build/ + dist/ first

Output:
    dist/void-hunter.exe              ~ single self-extracting executable

Size: ~120-180 MB (Python runtime + pygame + all Assets bundled inside).
Startup: ~3-5s extra on first launch (self-extracts to tempdir).
"""
from pathlib import Path
import sys

# Resolve project root so the spec is location-independent.
PROJECT_ROOT = Path(SPECPATH).resolve()  # SPECPATH is injected by PyInstaller

block_cipher = None

a = Analysis(
    [str(PROJECT_ROOT / "main.py")],
    pathex=[str(PROJECT_ROOT)],
    binaries=[],
    # BLOQUE 58.45: bundle the Assets/ folder so the background image
    # and the 2 WAV music files end up next to the .exe at runtime.
    # `src.audio.music._find_assets_dir` and `src.ui.tiling_image.
    # _find_assets_dir` both probe `<sys._MEIPASS>/Assets/` first (which
    # is where PyInstaller drops these data files in onedir mode), so
    # the game finds them automatically with no code changes.
    datas=[
        # BLOQUE 58.12: bundle ONLY the runtime assets, not the dev
        # references (Bezier curves.mp4, etc). We split the Assets
        # folder so the .exe stays small (~180 MB instead of ~230 MB).
        # The runtime needs: backgrounds, sprites, music .wav files.
        (str(PROJECT_ROOT / "Assets" / "background"), "Assets/background"),
        (str(PROJECT_ROOT / "Assets" / "sprites"), "Assets/sprites"),
        # Music files (BLOQUE 58.45): only the runtime wav files, not
        # dev references. The 2 voice clips are tiny.
        (str(PROJECT_ROOT / "Assets" / "pantalla principal.wav"), "Assets"),
        (str(PROJECT_ROOT / "Assets" / "keep kept - Lerius - soundtrack gameplay.wav"), "Assets"),
        (str(PROJECT_ROOT / "Assets" / "voice_pantalla_principal.wav"), "Assets"),
        (str(PROJECT_ROOT / "Assets" / "voice_act_cleared.wav"), "Assets"),
        (str(PROJECT_ROOT / "Assets" / "voice_jefe.wav"), "Assets"),
        # BLOQUE 58.14: pre-generated lowpass-filtered BGM (avoid 8s
        # delay on the first pause). Generated by tools/debug_lowpass.py
        # from the original WAV at 600Hz cutoff. Safe to omit — the
        # game will regenerate on first pause if missing.
        (str(PROJECT_ROOT / "Assets" / "keep kept - Lerius - soundtrack gameplay_lp600.wav"), "Assets"),
        # BLOQUE 58.59: bundle the cinematic video PNG sequences
        # (V1-G title + V2-G zoom). ~5 MB total for 240x360 @ 30FPS.
        (str(PROJECT_ROOT / "Assets" / "video"), "Assets/video"),
        # BLOQUE 58.60: ship sprite sheets (reference assets used by
        # the in-game gallery: press S on the title screen to view).
        (str(PROJECT_ROOT / "Assets" / "sprites" / "player_ships" / "ship_01_spritesheet.png"), "Assets/sprites/player_ships"),
        (str(PROJECT_ROOT / "Assets" / "sprites" / "player_ships" / "ship_02_spritesheet.png"), "Assets/sprites/player_ships"),
        (str(PROJECT_ROOT / "Assets" / "sprites" / "player_ships" / "ship_03_spritesheet.png"), "Assets/sprites/player_ships"),
        (str(PROJECT_ROOT / "Assets" / "sprites" / "player_ships" / "ship_04_spritesheet.png"), "Assets/sprites/player_ships"),
        (str(PROJECT_ROOT / "Assets" / "sprites" / "player_ships" / "ship_05_spritesheet.png"), "Assets/sprites/player_ships"),
    ],
    hiddenimports=[
        # pygame submodules that PyInstaller's static analysis can miss.
        "pygame",
        "pygame.mixer",
        "pygame.font",
        "pygame.image",
        "pygame.transform",
        "pygame.draw",
        "pygame.surface",
        "pygame.time",
        "pygame.event",
        "pygame.display",
        "pygame.key",
        "pygame.mouse",
        "pygame.joystick",
        "pygame.scrap",
        "pygame.sndarray",
        "pygame.surfarray",
        "pygame.math",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Strip unused heavy stdlib to keep the .exe lean.
        "tkinter",
        "unittest",
        "xml",
        "xmlrpc",
        "pydoc",
        "doctest",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,   # BLOQUE 58.next: onefile mode — bundle binaries inside .exe
    a.zipfiles,
    a.datas,
    [],
    exclude_binaries=False,  # onefile: everything is in the .exe (no _internal/)
    name="void-hunter",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # UPX would shrink but adds AV false-positive risk
    console=False,  # GUI subsystem on Windows (no terminal window)
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon=str(PROJECT_ROOT / "tools" / "playtest_out" / "polish_29_goliath_phase1.png"),  # uncomment if you add an .ico
)

# BLOQUE 58.next: removed COLLECT step. Onefile mode produces a single
# dist/void-hunter.exe (~120-180 MB) instead of dist/void-hunter/ directory
# with .exe + _internal/. Trades startup time (~3-5s self-extract) for
# true single-file portability — the user can download one .exe and run
# it without needing any companion files.
