"""Stage 2: Post-process asteroid AI bases into transparent sprites (BLOQUE 61 + 64.A).

For each variant in asteroid_manifest.json:
  1. Load the 1024x1024 base PNG.
  2. Crop the bottom 15% (removes the "Generated by MiniMax AI" watermark).
  3. Center-crop to square (asteroids are already top-down, no rotation).
  4. Run pre-resize transparentize (catches pure black/white damero).
  5. LANCZOS resize to the target size (default 64x64 in BLOQUE 64.A; was 32x32).
  6. Run post-resize damero clean (`_transparentize_damero_after_resize`).
  7. Threshold alpha to binary.
  8. Save as Assets/sprites/asteroids/<variant>.png.

BLOQUE 64.A: the --size flag selects the output sprite resolution. The
default is 64 (the BLOQUE 64.A spec). Pass --size 32 to regenerate the
older 32x32 sprites for backward compat.

Usage:
    python tools/redesign_asteroids/02_postprocess.py             # 64x64 (BLOQUE 64.A)
    python tools/redesign_asteroids/02_postprocess.py --size 32   # legacy 32x32
    python tools/redesign_asteroids/02_postprocess.py --asteroid round
    python tools/redesign_asteroids/02_postprocess.py --force
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from PIL import Image

from tools.redesign_asteroids._asteroid_specs import ASTEROIDS
# Re-use the same transparentize helpers from the ship redesign pipeline.
# `02_postprocess.py` has a numeric prefix, so we load it via importlib.
import importlib
_postprocess_mod = importlib.import_module("tools.redesign_ships.02_postprocess")
_transparentize_background = _postprocess_mod._transparentize_background
_transparentize_damero_after_resize = _postprocess_mod._transparentize_damero_after_resize

BASE_DIR = PROJECT_ROOT / "Assets" / "sprites" / "redesign" / "_base"
SPRITES_DIR = PROJECT_ROOT / "Assets" / "sprites" / "asteroids"
MANIFEST_PATH = PROJECT_ROOT / "tools" / "redesign_asteroids" / "asteroid_manifest.json"
# BLOQUE 64.A: default to 64 (was 32 in BLOQUE 61). The --size flag
# overrides this for backward compat.
DEFAULT_SOURCE_SIZE = 64
WATERMARK_CROP_BOTTOM_PCT = 0.15


def load_base(key: str) -> Image.Image:
    base_path = BASE_DIR / f"asteroid_{key}_base.png"
    if not base_path.exists():
        raise FileNotFoundError(f"missing base: {base_path} (run Stage 1 first)")
    return Image.open(base_path).convert("RGBA")


def preprocess_base(base: Image.Image) -> Image.Image:
    """Crop bottom 15% (watermark), center-crop to square, transparentize.

    Asteroids are top-down, no rotation needed.
    """
    w, h = base.size
    # Crop bottom 15% off
    crop_h = int(h * (1 - WATERMARK_CROP_BOTTOM_PCT))
    cropped = base.crop((0, 0, w, crop_h))
    # Center-crop to square
    rw, rh = cropped.size
    side = min(rw, rh)
    left = (rw - side) // 2
    top = (rh - side) // 2
    square = cropped.crop((left, top, left + side, top + side))
    return _transparentize_background(square)


def make_sprite_png(base: Image.Image, out_path: Path, size: int) -> None:
    """Preprocess base → downscale to `size`x`size` → second-pass damero
    clean → threshold alpha → save."""
    square = preprocess_base(base)
    small = square.resize((size, size), Image.LANCZOS)
    # Second-pass damero clean AFTER resize (LANCZOS blends edges into mid-gray)
    small = _transparentize_damero_after_resize(small)
    # Threshold alpha to binary
    r, g, b, a = small.split()
    a = a.point(lambda v: 255 if v >= 128 else 0)
    out = Image.merge("RGBA", (r, g, b, a))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out.save(out_path)


def postprocess_one(key: str, size: int, force: bool = False) -> None:
    out_path = SPRITES_DIR / f"{key}.png"
    if not force and out_path.exists():
        # BLOQUE 64.A: only skip if the existing file is the right size.
        try:
            with Image.open(out_path) as existing:
                if existing.size == (size, size):
                    print(f"[skip] {key} (already exists at {size}x{size}: {out_path})")
                    return
                else:
                    print(f"[regen] {key} (size mismatch: {existing.size} != ({size}, {size}))")
        except Exception:
            pass
    print(f"[src ] {key} -> {size}x{size}")
    base = load_base(key)
    make_sprite_png(base, out_path, size)
    print(f"        saved: {out_path}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--asteroid", help="Post-process only this asteroid key")
    parser.add_argument(
        "--size",
        type=int,
        default=DEFAULT_SOURCE_SIZE,
        help=f"Output sprite resolution (default {DEFAULT_SOURCE_SIZE} for BLOQUE 64.A)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Regenerate the sprite even if a matching-size file already exists",
    )
    args = parser.parse_args()
    if not MANIFEST_PATH.exists():
        print("asteroid_manifest.json not found; run Stage 1 first")
        return 1
    if args.size not in (32, 64):
        print(f"unsupported size {args.size}; supported: 32, 64")
        return 1
    targets = ASTEROIDS if not args.asteroid else [a for a in ASTEROIDS if a.key == args.asteroid]
    if args.asteroid and not targets:
        print(f"unknown asteroid: {args.asteroid}")
        return 1
    for spec in targets:
        postprocess_one(spec.key, size=args.size, force=args.force)
    print(f"\nDone. {len(targets)} asteroid sprite(s) post-processed at {args.size}x{args.size}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
