"""Stage 2: Post-process AI bases into 32x32 source + animation frames (BLOQUE 59).

For each ship in manifest.json:
  1. Load the 1024x1024 base PNG.
  2. Crop the bottom 15% (removes the "Generated by MiniMax AI" watermark).
  3. Rotate 90 CCW (the AI gives side-view ships facing right; we want
     them facing up in the playfield).
  4. Resize to 32x32 with LANCZOS.
  5. Map pixels to the 64-color palette.
  6. Save as <ship>/_source.png.
  7. Generate 10 frames each for idle/thrust/damage/death.
  8. Save per-frame PNGs to <ship>/<animation>/frame_NN.png.

Usage:
    python tools/redesign_ships/02_postprocess.py
    python tools/redesign_ships/02_postprocess.py --ship enemy_scout
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from PIL import Image

from tools.redesign_ships._animation_frames import (
    generate_death_frames,
    generate_damage_frames,
    generate_idle_frames,
    generate_thrust_frames,
)
from tools.redesign_ships._palette_map import map_image_to_palette
from tools.redesign_ships._ship_specs import SHIPS

BASE_DIR = PROJECT_ROOT / "Assets" / "sprites" / "redesign" / "_base"
REDESIGN_DIR = PROJECT_ROOT / "Assets" / "sprites" / "redesign"
MANIFEST_PATH = PROJECT_ROOT / "tools" / "redesign_ships" / "manifest.json"
SOURCE_SIZE = 32
WATERMARK_CROP_BOTTOM_PCT = 0.15  # remove bottom 15% of base (watermark region)


def load_base(spec_key: str) -> Image.Image:
    base_path = BASE_DIR / f"{spec_key}_base.png"
    if not base_path.exists():
        raise FileNotFoundError(f"missing base: {base_path} (run Stage 1 first)")
    return Image.open(base_path).convert("RGBA")


def preprocess_base(base: Image.Image) -> Image.Image:
    """Crop bottom 15% (watermark), rotate 90 CCW (face up), center-crop square."""
    w, h = base.size
    # Crop bottom 15% off
    crop_h = int(h * (1 - WATERMARK_CROP_BOTTOM_PCT))
    cropped = base.crop((0, 0, w, crop_h))
    # Rotate 90 CCW so the ship's nose points up
    rotated = cropped.rotate(90, expand=True)
    # Center-crop to square (rotated may be wider than tall now)
    rw, rh = rotated.size
    side = min(rw, rh)
    left = (rw - side) // 2
    top = (rh - side) // 2
    square = rotated.crop((left, top, left + side, top + side))
    return square


def make_source_png(base: Image.Image, out_path: Path) -> None:
    """Preprocess base → downscale to 32x32 → map to palette → save."""
    square = preprocess_base(base)
    small = square.resize((SOURCE_SIZE, SOURCE_SIZE), Image.LANCZOS)
    rgb = map_image_to_palette(small.convert("RGB"))
    r, g, b = rgb.split()
    a = small.split()[3]
    out = Image.merge("RGBA", (r, g, b, a))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out.save(out_path)


def postprocess_one(spec_key: str) -> None:
    ship_dir = REDESIGN_DIR / spec_key
    source_path = ship_dir / "_source.png"
    if not source_path.exists():
        print(f"[src ] {spec_key}")
        base = load_base(spec_key)
        make_source_png(base, source_path)
    source = Image.open(source_path).convert("RGBA")
    for gen_fn, anim in [
        (generate_idle_frames, "idle"),
        (generate_thrust_frames, "thrust"),
        (generate_damage_frames, "damage"),
        (generate_death_frames, "death"),
    ]:
        out_dir = ship_dir / anim
        if all((out_dir / f"frame_{i:02d}.png").exists() for i in range(10)):
            print(f"[skip] {spec_key}/{anim} (all 10 frames exist)")
            continue
        print(f"[anim] {spec_key}/{anim}")
        gen_fn(source, out_dir)
    print(f"        done: {ship_dir}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ship", help="Post-process only this ship key")
    args = parser.parse_args()
    if not MANIFEST_PATH.exists():
        print("manifest.json not found; run Stage 1 first")
        return 1
    targets = SHIPS if not args.ship else [s for s in SHIPS if s.key == args.ship]
    if args.ship and not targets:
        print(f"unknown ship: {args.ship}")
        return 1
    for spec in targets:
        postprocess_one(spec.key)
    print(f"\nDone. {len(targets)} ship(s) post-processed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
