"""Procedural mountain layers with parallax scrolling.

Each `MountainLayer` draws a silhouette polygon along the bottom of the
playfield. The silhouette is generated by summing several sine waves
at different frequencies (a poor-man's value noise) and a per-layer
seed offset, so every layer looks distinct.

The world `x` is shifted by a per-layer scroll speed times elapsed
time, so layers further from the camera move slower than the
foreground. This is the parallax trick that makes the player feel
they are flying over a planet surface.

The polygon is filled with a single color, so layers compose cleanly
without alpha blending: background (lightest) drawn first, foreground
( darkest ) drawn on top.
"""
from __future__ import annotations

import math
from typing import Sequence

import pygame


class MountainLayer:
    """One silhouette band that scrolls right-to-left at `scroll_speed`.

    Args:
        horizon_y: the y coordinate where the mountain ridge sits.
            The polygon rises UP from this baseline (smaller y = taller).
        max_height: maximum peak height in pixels above the baseline.
        color: fill color for the polygon.
        scroll_speed: pixels per second the layer scrolls to the LEFT.
        seed: integer seed; different seeds give different silhouettes.
        octaves: list of (frequency, amplitude) pairs that sum into
            the silhouette. Defaults give a natural-looking ridge.
    """

    def __init__(
        self,
        horizon_y: int,
        max_height: int,
        color: tuple,
        scroll_speed: float,
        seed: int = 0,
        octaves: Sequence[tuple] = (
            (0.012, 1.00),
            (0.028, 0.55),
            (0.062, 0.28),
            (0.135, 0.14),
        ),
    ) -> None:
        self.horizon_y = horizon_y
        self.max_height = max_height
        self.color = color
        self.scroll_speed = scroll_speed
        self.seed = seed
        self.octaves = tuple(octaves)
        # Pre-compute per-octave phase offsets so all layers with the
        # same seed look identical (useful for repro / unit tests) but
        # different seeds diverge immediately.
        self._phases = [
            (seed * 7919 + i * 313) * 0.001 for i in range(len(self.octaves))
        ]
        # Cached point list (rebuilt each frame from current scroll).
        self._points: list[tuple[int, int]] = []

    def _height_at(self, world_x: float) -> float:
        """Sum of sines for this layer at world coordinate `world_x`."""
        h = 0.0
        for (freq, amp), phase in zip(self.octaves, self._phases):
            h += amp * math.sin(world_x * freq * 6.2831853 + phase * 6.2831853)
        # `h` is in [-1, 1] (sum of amps <= 1.97 in the default set).
        # Normalize to [0, 1] then scale.
        h = (h + 2.0) * 0.25  # rough remap so peaks hit ~1.0
        if h < 0.0:
            h = 0.0
        if h > 1.0:
            h = 1.0
        return h * self.max_height

    def update(self, dt: float) -> None:
        """Advance the scroll position. Cheap, no allocations."""
        # `scroll_offset` is the world x that is currently at screen x=0.
        # It increases over time (camera moves right in world space).
        self._scroll_offset = getattr(self, "_scroll_offset", 0.0) + self.scroll_speed * dt

    def draw(self, surface: pygame.Surface, screen_w: int) -> None:
        """Draw the silhouette polygon across the full screen width."""
        # Rebuild the point list each frame (small, ~screen_w points).
        points: list[tuple[int, int]] = []
        # Sample one point per pixel for a smooth polygon.
        # The world x at screen x = scroll_offset + x.
        scroll = getattr(self, "_scroll_offset", 0.0)
        for x in range(screen_w):
            world_x = scroll + x
            h = self._height_at(world_x)
            # h is how far ABOVE the baseline the ridge rises.
            y = int(self.horizon_y - h)
            points.append((x, y))
        # Close the polygon: down the right side, across the bottom,
        # and up the left side, so the fill covers the area BELOW the
        # ridge.
        points.append((screen_w - 1, self.horizon_y + 2))
        points.append((0, self.horizon_y + 2))
        pygame.draw.polygon(surface, self.color, points)
