"""Parallax background - 5 star layers + scrolling galaxy strip + planets.

The background is a SCROLLING STRIP (BLOQUE 58.15) that runs continuously
top-to-bottom, giving the player the sense of moving up through deep
space. The strip is:

  - 480 px wide (wider than the 320 px playfield, so the side edges
    show partial galaxies that "enter" and "exit" the viewport -
    creates depth)
  - 1440 px tall (3x the playfield height, so the wrap is not too
    tight and we have room for a few galaxies + procedural stars)
  - Composed of 3 large galaxy sprites + 2 small companion galaxies
    + ~70 procedural stars + a soft glow overlay
  - Picked from 4 variants (one per act) by set_theme() / set_strip_variant()

The strip scrolls downward at 25 px/s (between the slowest star
layer at 20 and the next at 50). On wrap, the player sees a new
arrangement of galaxies every ~58 seconds.

The previous BLOQUE 58.next system (1+ nebula with state machine
fade/reposition) is GONE. The strip replaces it.

Stars tile vertically (5 layers at speeds 20/50/100/180/280 px/s,
GDD section 4). Planets spawn on a timer with a slow rotation.

Dependencies: pygame, settings, palette, easing.
"""
from __future__ import annotations

import math
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import pygame

from src.core.settings import INTERNAL_H, INTERNAL_W
from src.utils.palette import get_theme


# Path to the 4 pixel art galaxy tints. Each is a tinted version of
# the user reference galaxy, generated by tools/tint_galaxy_sprites.py
# (HSL hue rotation, preserves saturation/lightness).
_THIS_DIR = Path(__file__).resolve().parent
_GALAXY_SPRITE_PATHS: tuple[Path, ...] = tuple(
    _THIS_DIR.parent.parent / "Assets" / "background" / f"galaxy_pixelart_{suffix}.png"
    for suffix in ("blue", "red", "cyan", "violet")
)
_GALAXY_FALLBACK_RADIUS_PX = 60


# Star layer scroll speeds (px/s). Layer 0 = farthest, slowest.
LAYER_SPEEDS: tuple[int, ...] = (20, 50, 100, 180, 280)
NUM_LAYERS = 5

# Star count per layer (per screen height)
# BLOQUE 58.12: lowered from 50 to 12 default - sparse look, ~80% black space.
STARS_PER_LAYER_DEFAULT = 12

# Planet spawn timer (seconds)
PLANET_SPAWN_MIN_S = 8.0
PLANET_SPAWN_MAX_S = 18.0

# Planet sizes (radius in px)
PLANET_RADIUS_MIN = 8
PLANET_RADIUS_MAX = 24

# Backward-compat alias (used by some tests)
STARS_PER_LAYER = STARS_PER_LAYER_DEFAULT


# BLOQUE 58.15: galaxy strip constants.
# The strip is wider than the playfield (480 vs 320) so the sides
# show partial galaxies for a "depth" effect. The strip is 3x the
# playfield height (1440 vs 480) so the wrap is not too obvious.
GALAXY_STRIP_W = 480
GALAXY_STRIP_H = 1440
# Scroll speed: between slowest star layer (20) and second (50).
# 25 px/s gives ~58s for one full wrap.
GALAXY_STRIP_SPEED = 25.0
# X offset to center the wider strip on the playfield.
# (480 - 320) / 2 = 80 px offset to the left so the playfield sees
# the middle 320 of the 480.
GALAXY_STRIP_X_OFFSET = (GALAXY_STRIP_W - INTERNAL_W) // 2
# BLOQUE 58.62 v3: matches the hand-painted reference. 7 main galaxies
# (one per vertical section of ~200px) + 4-6 small companions clustered
# around each main + 80 procedural stars. The user accepted the v2
# sparse look but said it was "too empty" vs the reference; the v3
# numbers approximate the reference's per-section composition.
#
# Per-section composition:
#   - 1 main galaxy (50-70 px radius, the visual anchor of the section)
#   - 4-6 small companions (15-30 px, within 80-150 px of the main)
#   - ~11 stars (out of 80 total / 7 sections)
#
# Total per strip: 7 + 28-42 = 35-49 galaxies + 80 stars = 115-129 elements.

# --- Main galaxies (7 sections, evenly distributed vertically) ---
STRIP_MAIN_GALAXIES: int = 7
STRIP_MAIN_RADIUS_MIN: int = 50
STRIP_MAIN_RADIUS_MAX: int = 70
# Uses sprite_indices[i % len(sprite_indices)] round-robin.

# --- Small companions (clustered around each main) ---
STRIP_COMPANION_GALAXIES_MIN: int = 4
STRIP_COMPANION_GALAXIES_MAX: int = 6
STRIP_COMPANION_RADIUS_MIN: int = 15
STRIP_COMPANION_RADIUS_MAX: int = 30
STRIP_COMPANION_DISTANCE_MIN: int = 80  # px from main center
STRIP_COMPANION_DISTANCE_MAX: int = 150

# --- Procedural stars (matches reference: many small + a few bright) ---
STRIP_PROCEDURAL_STARS: int = 80
# 60% small dim / 30% medium / 10% bright white.

# --- Edge padding (galaxies stay this many px from the top/bottom seam) ---
# BLOQUE 58.62: reduced from 200 to 50. With 200, the top and bottom
# 14% of the strip were empty (28% total) and the player saw a "gap"
# of empty space at every wrap. With 50, galaxies can live in 93% of
# the strip height so the wrap is continuous.
STRIP_EDGE_PAD: int = 50
# Variant names (mapped to theme names). Order matters: this also
# serves as the canonical act index -> theme name mapping.
_STRIP_VARIANT_THEMES: tuple[str, ...] = (
    "blue_void",   # 0: act 1 - blue
    "teal",        # 1: act 2 - green
    "gold_amber",  # 2: act 3 - yellow/cream
    "purple_dusk", # 3: act 4 - violet/purple
)
# Per-variant preferred galaxy sprite indices (which of the 4 tints
# to use for the galaxies in this strip). Each variant gets 2 of the 4.
_STRIP_VARIANT_SPRITE_INDICES: tuple[tuple[int, ...], ...] = (
    (0, 3),        # 0 blue: blue + violet
    (2, 0),        # 1 green (teal): cyan + blue
    (1, 2),        # 2 yellow (gold_amber): red + cyan
    (3, 1),        # 3 violet (purple_dusk): violet + red
)
# Per-variant deterministic seeds so each variant is reproducible.
_STRIP_VARIANT_SEEDS: tuple[int, ...] = (
    0xB0DE_0001,
    0xB0DE_0002,
    0xB0DE_0003,
    0xB0DE_0004,
)


@dataclass
class Star:
    """Single star with twinkle state."""
    x: float
    y: float
    layer: int
    base_alpha: int
    twinkle_phase: float


@dataclass
class Planet:
    """Single planet with atmosphere + ring."""
    x: float
    y: float
    radius: int
    color: tuple[int, int, int]
    ring_color: tuple[int, int, int]
    ring_angle: float = 0.0
    ring_width: int = 2


class ParallaxBackground:
    """5-layer parallax + scrolling galaxy strip + planet atmosphere.

    Per GDD section 11: parallax render <0.40ms.
    BLOQUE 58.15: the galaxy strip replaces the BLOQUE 58.next
    single-nebula system. The strip is a tall 480x1440 Surface that
    scrolls downward continuously. There are 4 strip variants, one
    per act, picked by set_theme() / set_strip_variant().
    """

    def __init__(
        self,
        width: int = INTERNAL_W,
        height: int = INTERNAL_H,
        rng_seed: int | None = 42,
        stars_per_layer: int = STARS_PER_LAYER_DEFAULT,
        spawn_planets: bool = True,
    ) -> None:
        """BLOQUE 58.15: star layers + scrolling galaxy strip + planet.

        Args:
            stars_per_layer: number of stars per parallax layer.
                Default 12 (sparse, ~80% black). Title screen overrides
                to 50 for the dense look.
            spawn_planets: if False, no planets spawn. Default True (title).
        """
        self._w = width
        self._h = height
        self._rng = random.Random(rng_seed)
        self._stars: list[Star] = []
        self._planet: Optional[Planet] = None
        self._planet_timer: float = PLANET_SPAWN_MIN_S
        # Lazy-loaded galaxy sprite cache. Filled on first strip render.
        self._galaxy_sprites: Optional[list[pygame.Surface]] = None
        # Strip variant index (0..3)
        self._strip_variant: int = 0
        # Cached strip surface per variant
        self._strip_surfaces: dict[int, pygame.Surface] = {}
        # Scroll offset (px)
        self._strip_y_offset: float = 0.0
        self._t: float = 0.0
        self._theme_name: str = _STRIP_VARIANT_THEMES[0]
        self._stars_per_layer = stars_per_layer
        self._spawn_planets_enabled = spawn_planets
        # Render the initial strip eagerly
        self._get_or_render_strip(self._strip_variant)
        self._init_stars()

    def set_theme(self, name: str) -> None:
        """BLOQUE 58.15: theme change picks the matching strip variant."""
        self._theme_name = name
        try:
            variant = _STRIP_VARIANT_THEMES.index(name)
        except ValueError:
            variant = 0
        self.set_strip_variant(variant)

    def set_strip_variant(self, variant: int) -> None:
        """Pick a strip variant (0..3). Out-of-range clamps to 0."""
        self._strip_variant = max(0, min(len(_STRIP_VARIANT_THEMES) - 1, variant))
        self._theme_name = _STRIP_VARIANT_THEMES[self._strip_variant]
        self._get_or_render_strip(self._strip_variant)

    def get_strip_variant(self) -> int:
        return self._strip_variant

    def get_strip_height(self) -> int:
        return GALAXY_STRIP_H

    def get_strip_y_offset(self) -> float:
        return self._strip_y_offset

    @property
    def active_count(self) -> int:
        return (1 if self._strip_surfaces else 0) + len(self._stars) + (1 if self._planet else 0)

    def update(self, dt: float) -> None:
        if dt <= 0.0:
            return
        self._t += dt
        for s in self._stars:
            speed = LAYER_SPEEDS[s.layer]
            s.y += speed * dt
            if s.y > self._h:
                s.y -= self._h
        self._strip_y_offset = (self._strip_y_offset + GALAXY_STRIP_SPEED * dt) % GALAXY_STRIP_H
        if self._planet is not None:
            self._planet.ring_angle = (self._planet.ring_angle + 8.0 * dt) % 360.0
            self._planet.y += 12.0 * dt
            if self._planet.y - self._planet.radius > self._h:
                self._planet = None
        else:
            if not self._spawn_planets_enabled:
                return
            self._planet_timer -= dt
            if self._planet_timer <= 0.0:
                self._spawn_planet()
                self._planet_timer = self._rng.uniform(PLANET_SPAWN_MIN_S, PLANET_SPAWN_MAX_S)

    def draw(self, target: pygame.Surface) -> None:
        strip = self._strip_surfaces.get(self._strip_variant)
        if strip is not None:
            y = -self._strip_y_offset
            target.blit(strip, (GALAXY_STRIP_X_OFFSET, int(y)))
            target.blit(strip, (GALAXY_STRIP_X_OFFSET, int(y + GALAXY_STRIP_H)))
        for s in self._stars:
            twinkle = 0.7 + 0.3 * math.sin(self._t * 2.0 + s.twinkle_phase)
            a = int(min(255, s.base_alpha * twinkle))
            color = (200, 200, 220, a) if s.layer < 2 else (255, 255, 255, a)
            target.set_at((int(s.x), int(s.y) % self._h), color)
        if self._planet is not None:
            self._draw_planet(target, self._planet)

    def release_all(self) -> None:
        self._init_stars()
        self._planet = None
        self._planet_timer = PLANET_SPAWN_MIN_S
        self._t = 0.0
        self._strip_y_offset = 0.0

    def _init_stars(self) -> None:
        self._stars = []
        for layer in range(NUM_LAYERS):
            for _ in range(self._stars_per_layer):
                self._stars.append(Star(
                    x=self._rng.uniform(0, self._w),
                    y=self._rng.uniform(0, self._h),
                    layer=layer,
                    base_alpha=100 + layer * 30,
                    twinkle_phase=self._rng.uniform(0, 2 * math.pi),
                ))

    def _get_or_render_strip(self, variant: int) -> pygame.Surface:
        surf = self._strip_surfaces.get(variant)
        if surf is not None:
            return surf
        theme_name = _STRIP_VARIANT_THEMES[variant]
        seed = _STRIP_VARIANT_SEEDS[variant]
        theme = get_theme(theme_name)
        sprite_indices = _STRIP_VARIANT_SPRITE_INDICES[variant]
        surf = self._render_galaxy_strip(
            theme=theme, sprite_indices=sprite_indices, seed=seed,
        )
        self._strip_surfaces[variant] = surf
        return surf

    def _render_galaxy_strip(
        self,
        theme: dict,
        sprite_indices: tuple[int, ...],
        seed: int,
    ) -> pygame.Surface:
        sprites = self._load_galaxy_sprites()
        if not sprites:
            surf = pygame.Surface((GALAXY_STRIP_W, GALAXY_STRIP_H), pygame.SRCALPHA)
            surf.fill(theme.get("bg", (0, 0, 0)))
            return surf
        rng = random.Random(seed)
        surf = pygame.Surface((GALAXY_STRIP_W, GALAXY_STRIP_H), pygame.SRCALPHA)
        surf.fill(theme.get("bg", (0, 0, 0)))

        # 1) Procedural stars (down from 70 to 20 per the BLOQUE 58.62 spec)
        star_swatches = theme.get("stars", ((200, 200, 220), (255, 255, 255)))
        for _ in range(STRIP_PROCEDURAL_STARS):
            x = rng.uniform(0, GALAXY_STRIP_W)
            y = rng.uniform(0, GALAXY_STRIP_H)
            roll = rng.random()
            if roll < 0.70:
                color = star_swatches[0]
                radius = 1
            elif roll < 0.95:
                color = star_swatches[1]
                radius = 1
            else:
                color = (255, 255, 255)
                radius = 2
            pygame.draw.circle(surf, color, (int(x), int(y)), radius)

        # 2) Main galaxies: STRIP_MAIN_GALAXIES (7) of them, distributed
        # in vertical sections. Each main is the visual anchor of its
        # section (~200px tall band in the 1440-tall strip). The
        # distribution is evenly spaced (not random) so the player sees
        # a consistent rhythm as the strip scrolls past.
        section_h = GALAXY_STRIP_H / STRIP_MAIN_GALAXIES
        for i in range(STRIP_MAIN_GALAXIES):
            # x: random in the strip width (with side padding)
            main_x = rng.uniform(40, GALAXY_STRIP_W - 40)
            # y: centered in the section, with some jitter so they don't
            # all sit on a perfect grid
            section_center_y = (i + 0.5) * section_h
            jitter = rng.uniform(-section_h * 0.25, section_h * 0.25)
            main_y = section_center_y + jitter
            # Clamp to EDGE_PAD bounds (just in case jitter pushes too far)
            main_y = max(STRIP_EDGE_PAD, min(GALAXY_STRIP_H - STRIP_EDGE_PAD, main_y))
            main_radius = rng.uniform(STRIP_MAIN_RADIUS_MIN, STRIP_MAIN_RADIUS_MAX)
            main_sprite_idx = sprite_indices[i % len(sprite_indices)]
            self._blit_galaxy_scaled(
                surf, sprites[main_sprite_idx], main_x, main_y, main_radius
            )

            # 3) Small companions: 4-6 clustered around this main galaxy.
            # Each main is the "center" of a section; the companions give
            # the section the "solar system" feel from the reference.
            n_companions = rng.randint(
                STRIP_COMPANION_GALAXIES_MIN, STRIP_COMPANION_GALAXIES_MAX
            )
            for _ in range(n_companions):
                angle = rng.uniform(0, 2 * math.pi)
                distance = rng.uniform(
                    STRIP_COMPANION_DISTANCE_MIN, STRIP_COMPANION_DISTANCE_MAX
                )
                cx = main_x + math.cos(angle) * distance
                cy = main_y + math.sin(angle) * distance
                # Clamp into strip bounds (companions can sit close to
                # edges for depth, but not on the wrap seam)
                cx = max(20, min(GALAXY_STRIP_W - 20, cx))
                cy = max(STRIP_EDGE_PAD, min(GALAXY_STRIP_H - STRIP_EDGE_PAD, cy))
                radius = rng.uniform(
                    STRIP_COMPANION_RADIUS_MIN, STRIP_COMPANION_RADIUS_MAX
                )
                companion_sprite_idx = sprite_indices[1 % len(sprite_indices)]
                self._blit_galaxy_scaled(
                    surf, sprites[companion_sprite_idx], cx, cy, radius
                )

        # 4) Glow overlay (unchanged from BLOQUE 58.15)
        self._draw_glow_overlay(surf, theme)
        return surf

    def _blit_galaxy_scaled(
        self,
        target: pygame.Surface,
        sprite: pygame.Surface,
        cx: float,
        cy: float,
        target_radius: float,
    ) -> None:
        sw, sh = sprite.get_size()
        if sw == 0 or sh == 0:
            return
        size = max(8, int(target_radius * 2))
        scale = min(size / sw, size / sh)
        new_w = max(1, int(sw * scale))
        new_h = max(1, int(sh * scale))
        scaled = pygame.transform.scale(sprite, (new_w, new_h))
        blit_x = int(cx - new_w / 2)
        blit_y = int(cy - new_h / 2)
        target.blit(scaled, (blit_x, blit_y))

    def _draw_glow_overlay(self, surf: pygame.Surface, theme: dict) -> None:
        """Soft vertical gradient (parabolic: 0 at edges, peak at center).
        Replaces the 3-band version which was visible as a hard horizontal
        line in the playfield view.
        """
        accent = theme.get("accent", (60, 60, 80))
        max_alpha = 18
        for y in range(GALAXY_STRIP_H):
            t = (y / GALAXY_STRIP_H) * 2.0 - 1.0
            factor = max(0.0, 1.0 - t * t)
            alpha = int(max_alpha * factor)
            if alpha == 0:
                continue
            band = pygame.Surface((GALAXY_STRIP_W, 1), pygame.SRCALPHA)
            band.fill((*accent, alpha))
            surf.blit(band, (0, y))

    def _load_galaxy_sprites(self) -> list[pygame.Surface]:
        if self._galaxy_sprites is not None:
            return self._galaxy_sprites
        loaded: list[pygame.Surface] = []
        for path in _GALAXY_SPRITE_PATHS:
            try:
                raw = pygame.image.load(str(path))
                try:
                    surf = raw.convert_alpha()
                except pygame.error:
                    surf = raw
                loaded.append(surf)
            except (pygame.error, FileNotFoundError, OSError):
                continue
        self._galaxy_sprites = loaded
        return loaded

    def _spawn_planet(self) -> None:
        theme = get_theme(self._theme_name)
        self._planet = Planet(
            x=self._rng.uniform(self._w * 0.2, self._w * 0.8),
            y=-self._rng.uniform(20, 40),
            radius=self._rng.randint(PLANET_RADIUS_MIN, PLANET_RADIUS_MAX),
            color=theme.get("accent", (200, 200, 200)),
            ring_color=theme.get("accent", (200, 200, 200)),
        )

    def _draw_planet(self, target: pygame.Surface, p: Planet) -> None:
        cx, cy = int(p.x), int(p.y)
        halo = pygame.Surface((p.radius * 4, p.radius * 4), pygame.SRCALPHA)
        for r in range(p.radius * 2, 0, -1):
            a = int(40 * (r / (p.radius * 2.0)))
            pygame.draw.circle(halo, (*p.color, a), (halo.get_width() // 2, halo.get_height() // 2), r)
        target.blit(halo, (cx - halo.get_width() // 2, cy - halo.get_height() // 2))
        pygame.draw.circle(target, p.color, (cx, cy), p.radius)
        outline_color = (max(0, p.color[0] - 40), max(0, p.color[1] - 40), max(0, p.color[2] - 40))
        pygame.draw.circle(target, outline_color, (cx, cy), p.radius, 1)
