"""TileManager: scrolls through 6 pre-baked 320x480 background tiles.

Each tile is one viewport. Sequenced top-to-bottom, the total height is
6 * 480 = 2880 px. At 12 px/s scroll speed, wrap time is 240s = 4 min.

Used by ParallaxBackground when use_tile_sequence=True (level 1).
The tiles themselves are AI-generated by tools/tiles/ai_gen/ and stored
in Assets/background/tiles/act1/.
"""
from __future__ import annotations

from pathlib import Path

import pygame


class TileManager:
    """Loads 6 tiles and draws them as a scrolling strip."""

    NUM_TILES = 6
    TILE_H = 480
    TILE_W = 320

    def __init__(self, tiles_dir: Path) -> None:
        self._tiles_dir = Path(tiles_dir)
        if not self._tiles_dir.exists():
            raise FileNotFoundError(f"Tiles directory not found: {self._tiles_dir}")
        self._tile_surfaces: list[pygame.Surface] = []
        for i in range(self.NUM_TILES):
            # tile_01_atmosphere_exit.png, tile_02_enter_belt.png, etc.
            candidates = sorted(self._tiles_dir.glob(f"tile_{i + 1:02d}_*.png"))
            if not candidates:
                raise FileNotFoundError(
                    f"Tile {i + 1} not found in {self._tiles_dir} "
                    f"(expected pattern tile_{i + 1:02d}_*.png)"
                )
            # Note: .convert() requires an initialized display, so we keep
            # the surface in its source format. The draw() blit works fine.
            self._tile_surfaces.append(pygame.image.load(str(candidates[0])))

    def get_height(self) -> int:
        return self.NUM_TILES * self.TILE_H

    def draw(self, target: pygame.Surface, scroll_y: float) -> None:
        """Draw the scrolling tile sequence to target.

        scroll_y in [0, 2880). The total scroll wraps modulo 2880.
        Tiles are also tiled horizontally to cover the full target width
        (in case the playfield is wider than TILE_W = 320).
        """
        h = self.get_height()
        scroll_y = scroll_y % h
        # We need to draw enough tiles to cover the target height (480).
        # A tile is visible from (tile_idx * 480) to ((tile_idx + 1) * 480)
        # in the strip coordinate system. The first tile partially visible
        # is at floor(scroll_y / 480).
        first_tile = int(scroll_y // self.TILE_H)
        y_in_first = scroll_y - first_tile * self.TILE_H
        target_w = target.get_width()
        for offset in range(2):  # 2 vertical tiles is enough to cover 480 px
            tile_idx = (first_tile + offset) % self.NUM_TILES
            y_screen = int(-y_in_first + offset * self.TILE_H)
            tile_surface = self._tile_surfaces[tile_idx]
            # Tile horizontally to cover full target width
            x = 0
            while x < target_w:
                target.blit(tile_surface, (x, y_screen))
                x += self.TILE_W
