"""Stage 1: Generate 4 MINE-ASTEROID base images via mcode-tools (BLOQUE 63).

For each of the 4 state machine frames (opening, open, closing, death),
calls mcode-tools to generate a 1024x1024 base image, downloads it,
saves to Assets/sprites/redesign/_base/, and logs the node_id + prompt
to a manifest.

The closed state (the perfect-camo asteroid look) is NOT generated by
AI — it's the literal byte-for-byte copy of
``Assets/sprites/asteroids/round.png`` (BLOQUE 61). See task 2.

The asteroid style anchor: the prompt is seeded with the same
constraints used for the BLOQUE 61 asteroid bases (round asteroid,
brown rocky palette, 16-bit pixel art, sharp edges).

Usage:
    cd D:\\AI\\void-hunter
    .venv\\Scripts\\python.exe tools/generate_mine_asteroid_bases.py
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from tools.redesign_ships._ai_client import download_node, generate_ship_base


# 4 state-specific bases. The "closed" state is the round asteroid
# lookalike (BLOQUE 61) and is NOT AI-generated.
MINE_STATES = (
    "opening",   # asteroid partially opening (panels splitting)
    "open",      # gun barrel visible, ready to fire
    "closing",   # panels coming back together
    "death",     # explosion / debris
)


# 1024x1024 base prompts. Each prompt is anchored on the round-asteroid
# aesthetic (brown rocky palette, 16-bit pixel art) so the MINE-ASTEROID
# blends in perfectly with regular asteroids when closed.
PROMPTS = {
    "opening": (
        "16-bit pixel art, single round asteroid in mid-open state, top-down view. "
        "A round brown rocky asteroid with a metal seam splitting open — the "
        "panels are partially separated revealing a small gun barrel inside. "
        "Background pure black, no shadows, no background details. "
        "Sharp clean pixel edges, no anti-aliasing, no gradients, limited palette "
        "(max 8 colors: brown, dark brown, light brown, gray, dark gray, light gray, "
        "black, white). Metal Slug aesthetic."
    ),
    "open": (
        "16-bit pixel art, single open mine weapon, top-down view. "
        "A round brown rocky asteroid with the top panel fully open, revealing "
        "a small dark gun barrel pointing down. The asteroid body is symmetric "
        "with two opened panels (left and right) showing the gun. "
        "Background pure black, no shadows, no background details. "
        "Sharp clean pixel edges, no anti-aliasing, no gradients, limited palette "
        "(max 8 colors: brown, dark brown, light brown, gray, dark gray, light gray, "
        "black, white). Metal Slug aesthetic."
    ),
    "closing": (
        "16-bit pixel art, single round asteroid in mid-close state, top-down view. "
        "A round brown rocky asteroid with panels coming back together after "
        "firing. A metal seam visible but panels are nearly rejoined. "
        "Background pure black, no shadows, no background details. "
        "Sharp clean pixel edges, no anti-aliasing, no gradients, limited palette "
        "(max 8 colors: brown, dark brown, light brown, gray, dark gray, light gray, "
        "black, white). Metal Slug aesthetic."
    ),
    "death": (
        "16-bit pixel art, single asteroid explosion, top-down view. "
        "A round brown rocky asteroid exploding — body fragmented into 6-8 rocky "
        "debris pieces radiating outward, with a yellow-orange-white fireball at "
        "the center. Background pure black, no shadows, no background details. "
        "Sharp clean pixel edges, no anti-aliasing, no gradients, limited palette "
        "(max 10 colors: brown, dark brown, light brown, gray, dark gray, light gray, "
        "black, white, yellow, orange). Metal Slug aesthetic."
    ),
}


BASE_DIR = PROJECT_ROOT / "Assets" / "sprites" / "redesign" / "_base"
MANIFEST_PATH = PROJECT_ROOT / "tools" / "manifest_mine_asteroid.json"


def load_manifest() -> dict:
    if MANIFEST_PATH.exists():
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    return {"bases": {}}


def save_manifest(m: dict) -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(m, indent=2), encoding="utf-8")


def generate_one(state: str, manifest: dict) -> None:
    out_path = BASE_DIR / f"mine_asteroid_{state}_base.png"
    if out_path.exists():
        print(f"[skip] mine_asteroid_{state}: {out_path} already exists")
        return
    print(f"[gen ] mine_asteroid_{state}")
    prompt = PROMPTS[state]
    node_id = generate_ship_base(prompt=prompt, output_file=str(out_path))
    print(f"        node_id={node_id}, downloading...")
    download_node(node_id, str(out_path))
    manifest["bases"][f"mine_asteroid_{state}"] = {
        "node_id": node_id,
        "prompt": prompt,
        "state": state,
        "out_path": str(out_path),
        "size_bytes": out_path.stat().st_size,
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
    save_manifest(manifest)
    print(f"        saved: {out_path} ({out_path.stat().st_size} bytes)")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--state", help="Regenerate only this state (opening|open|closing|death)")
    args = parser.parse_args()
    BASE_DIR.mkdir(parents=True, exist_ok=True)
    manifest = load_manifest()
    targets = MINE_STATES if not args.state else (args.state,)
    if args.state and args.state not in MINE_STATES:
        print(f"unknown state: {args.state} (expected one of {MINE_STATES})")
        return 1
    for state in targets:
        generate_one(state, manifest)
    print(f"\nDone. {len(targets)} base(s) processed. Manifest: {MANIFEST_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
